name: Publish to PowerShell Gallery

on:
  push:
    branches:
      - dev
    tags:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck

      - name: Run Tests
        shell: pwsh
        run: |
          $testResults = Invoke-Pester -Path .\YaugerAIO.tests.ps1 -Output Detailed -PassThru
          if ($testResults.FailedCount -gt 0) {
            throw "Tests failed. Please check the test results."
          }

      - name: Install PowerShell Gallery Tools
        shell: pwsh
        run: |
          Install-Module -Name PowerShellGet -Force -SkipPublisherCheck
          Install-Module -Name PSGalleryTools -Force -SkipPublisherCheck

      - name: Update Module Version
        shell: pwsh
        run: |
          $manifestPath = ".\YaugerAIO.psd1"
          $manifest = Import-PowerShellDataFile $manifestPath
          $version = $manifest.ModuleVersion

          # If this is a tag push, use the tag version
          if ($env:GITHUB_REF.StartsWith('refs/tags/v')) {
            $version = $env:GITHUB_REF.Replace('refs/tags/v', '')
          }

          # Update the manifest version
          $content = Get-Content $manifestPath -Raw
          $content = $content -replace "ModuleVersion = '.*'", "ModuleVersion = '$version'"
          Set-Content -Path $manifestPath -Value $content

      - name: Publish to PowerShell Gallery
        shell: pwsh
        env:
          PSGALLERY_API_KEY: ${{ secrets.PSG_TOKEN }}
        run: |
          $publishParams = @{
            Path = "."
            NuGetApiKey = $env:PSGALLERY_API_KEY
            Repository = "PSGallery"
            Force = $true
          }

          Publish-Module @publishParams

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this release

            - Initial release of YaugerAIO
            - Comprehensive system maintenance and optimization tools
            - Enhanced error handling and performance monitoring
            - Threaded operations for better performance

            For detailed information, please visit the [project page](https://github.com/yourGraytools/YaugerAIO).
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
